### ISSUE TITLE
External Sign In with Google/Facebook does not work (32 Bit Windows)

### ISSUE THREAD

**Issue by rilinium** [qfoxb/shellshock-electron#1]
Only opens a blank window that immediately closes

Edit by qfoxb: Only occurs now on 32 bit windows. Won't fix

**Comment by qfoxb** [comment]
what platform?

**Comment by qfoxb** [comment]
ok i can replicate on windows

**Comment by qfoxb** [comment]
This seems to be an issue with nativefier, will fix in next update

**Comment by femou1** [comment]
Still doesn't work on x32

**Comment by rilinium** [comment]
:trollface:

**Comment by qfoxb** [comment]
Can someone test if this is still an issue?
